name: Build

on: [push]

env:
  GO_VERSION: '1.23'
  GOLANG_CI_VERSION: '1.61'

jobs:

  linting:
    name: Linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: golangci/golangci-lint-action@v6
        name: "GolangCI-Lint ${{ env.GOLANG_CI_VERSION }}"
        with:
          version: v${{ env.GOLANG_CI_VERSION }}
          args: --timeout=5m

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Test
      run: go test ./...

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [linting, test]

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CONCORD_CLIENT_ID: ${{ secrets.OAUTH_CLIENT_ID }}
      CONCORD_CLIENT_SECRET: ${{ secrets.OAUTH_CLIENT_SECRET }}

    steps:
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Snapshot
      uses: goreleaser/goreleaser-action@v6
      with:
        distribution: goreleaser
        version: latest
        args: release --snapshot

    - name: Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: goreleaser/goreleaser-action@v6
      with:
        distribution: goreleaser
        version: latest
        args: release --clean
